PlayWell/PlayWell/Models/LegoList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayWell.Models
{
    public class LegoList
    {
        public int Id { get; set; }

        public string ApplicationUserId { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        public DateTime LastModified { get; set; }

        public string Name { get; set; }

        public virtual ICollection<ListBridge> ListBridges { get; set; }
    }
}

PlayWell/PlayWell/Controllers/LegoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlayWell.Data;
using PlayWell.Models;
using PlayWell.Models.ListViewModels;
using Microsoft.AspNetCore.Authorization;
using PlayWell.Models.InventoryViewModels;

namespace PlayWell.Controllers
{
    [Authorize]
    public class LegoListController : Controller
    {
        private readonly ApplicationDbContext context;

        public LegoListController(ApplicationDbContext context)
        {
            this.context = context;    
        }

        // GET: LegoList
        public IActionResult Index()
        {
            InventoryViewModel viewModel = new InventoryViewModel();
            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);
            viewModel.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);
        }

        // GET: LegoList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var legoList = await this.context.LegoLists
                .Include(l => l.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (legoList == null)
            {
                return NotFound();
            }

            return View(legoList);
        }

        // GET: LegoList/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(this.context.Users, "Id", "Id");
            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            return View();
        }

        // POST: LegoList/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ApplicationUserId,LastModified,Name")] LegoList legoList)
        {
            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);

            if (ModelState.IsValid)
            {
                if (currentUser != null)
                {
                    legoList.ApplicationUserId = currentUser.Id;
                }
                this.context.Add(legoList);
                await this.context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ApplicationUserId"] = new SelectList(this.context.Users, "Id", "Id", legoList.ApplicationUserId);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            return View(legoList);
        }

        // GET: LegoList/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var legoList = await this.context.LegoLists.SingleOrDefaultAsync(m => m.Id == id);
            if (legoList == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(this.context.Users, "Id", "Id", legoList.ApplicationUserId);
            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            return View(legoList);
        }

        // POST: LegoList/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ApplicationUserId,LastModified,Name")] LegoList legoList)
        {
            if (id != legoList.Id)
            {
                return NotFound();
            }

            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);

            if (ModelState.IsValid)
            {
                if (currentUser != null)
                {
                    legoList.ApplicationUserId = currentUser.Id;
                }

                try
                {
                    this.context.Update(legoList);
                    await this.context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LegoListExists(legoList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ApplicationUserId"] = new SelectList(this.context.Users, "Id", "Id", legoList.ApplicationUserId);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            return View(legoList);
        }

        // GET: LegoList/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var legoList = await this.context.LegoLists
                .Include(l => l.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (legoList == null)
            {
                return NotFound();
            }

            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();
            return View(legoList);
        }

        // POST: LegoList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var legoList = await this.context.LegoLists.SingleOrDefaultAsync(m => m.Id == id);
            this.context.LegoLists.Remove(legoList);
            await this.context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool LegoListExists(int id)
        {
            return this.context.LegoLists.Any(e => e.Id == id);
        }
    }
}

PlayWell/PlayWell/Views/LegoList/Create.cshtml
@model PlayWell.Models.LegoList

<div class="col-md-10">
    <div class="panel panel-primary">
        <div class="panel-heading"><h3>Create List</h3></div>

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LastModified" value="@DateTime.Now"/>
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </form>

        <br clear="all" /><br />
        <div style="margin-left:10px;">
            <a asp-action="Index">Back to List Manager</a>
        </div>

    </div>
</div>

PlayWell/PlayWell/Views/LegoList/Delete.cshtml
@model PlayWell.Models.LegoList

<div class="col-md-10">
    <div class="panel panel-primary">
        <div class="panel-heading"><h3>Delete List</h3></div>

        <div style="margin-left:10px;">
            <h3>Are you sure you want to delete this?</h3>

            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.LastModified)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LastModified)
                </dd>
            </dl>
        </div>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <div class="form-actions no-color" style="margin-left:10px;">
                <input type="submit" value="Delete" class="btn btn-default" />
                <br clear="all" /><br />
                <a asp-action="Index">Back to List Manager</a>
            </div>
        </form>

    </div>
</div>

PlayWell/PlayWell/Views/LegoList/Details.cshtml
@model PlayWell.Models.LegoList

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>LegoList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastModified)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastModified)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PlayWell/PlayWell/Views/LegoList/Edit.cshtml
@model PlayWell.Models.LegoList

<div class="col-md-10">
    <div class="panel panel-primary">
        <div class="panel-heading"><h3>Edit List</h3></div>

        <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Name" class="form-control" style="width:200px;" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
        </form>
        <br clear="all" /><br />
        <div style="margin-left:10px;">
            <a asp-action="Index">Back to List Manager</a>
        </div>

    </div>
</div>

PlayWell/PlayWell/Views/LegoList/Index.cshtml
@model PlayWell.Models.InventoryViewModels.InventoryViewModel

<div class="col-md-10">
    <div class="panel panel-primary">
        <div class="panel-heading"><h3>Manage Lists</h3></div>
        <br />
        <nav>
            <a asp-controller="LegoList" asp-action="Create" class="btn btn-default" style="margin-left: 10px;">Create List</a>
        </nav>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th colspan="4">Name</th>
                    <th colspan="1"># Items</th>
                    <th colspan="3">Last Modified</th>
                    <th colspan="2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (LegoList l in Model.LegoLists)
                {
                    <tr>
                        <td colspan="4">
                            <a href="http://playwellusa.com/Inventory/ItemList/?listId=@l.Id">@l.Name</a>
                        </td>
                        <td colspan="1">
                            @l.ListBridges.Count
                        </td>
                        <td colspan="3">
                            @l.LastModified
                        </td>
                        <td colspan="2">
                            <a asp-action="Edit" asp-route-id="@l.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@l.Id">Delete</a>
                        </td>
                    </tr>
                }
                @if (Model.LegoLists.Count == 0)
                {
                    <tr>
                        <td colspan="10">
                            No data to display.
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>