PlayWell/PlayWell/Models/InventoryViewModels/InventoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Playwell;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PlayWell.Models.InventoryViewModels
{
    public class InventoryViewModel
    {
        public string Filter { get; set; }

        public int Type { get; set; }

        public string View { get; set; }

        public int AmountToDisplay { get; set; }

        public LegoList ChosenList { get; set; }

        public List<LegoItem> LegoItems { get; set; }

        public IEnumerable<LegoColor> LegoColors { get; set; }

        public List<LegoList> LegoLists { get; set; }

        public IEnumerable<LegoType> LegoTypes { get; set; }

        public IEnumerable<PricingMethod> PricingMethods { get; set; }

        public decimal? MSRP { get; set; }

        public int Counter { get; set; }

        public string Previous { get; set; }

        public int PageNumber { get; set; }

        public int TotalResults { get; set; }

        public double TotalPages { get; set; }
    }
}

PlayWell/PlayWell/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlayWell.Data;
using PlayWell.Helper;
using PlayWell.Models;
using PlayWell.Models.InventoryViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PlayWell.Controllers
{
    [Authorize]
    public class InventoryController : Controller
    {
        private readonly ApplicationDbContext context;

        private static InventoryViewModel storedViewModel;

        private static List<LegoItem> favorites;

        private static bool filterChanged;

        private static bool startingOver;

        private IHostingEnvironment environment;

        private PricingHelper pricingHelper;

        public InventoryController(ApplicationDbContext context, IHostingEnvironment environment)
        {
            this.context = context;
            this.environment = environment;
            this.pricingHelper = new PricingHelper(context);
            if (storedViewModel == null)
            {
                storedViewModel = new InventoryViewModel();
            }

            if (storedViewModel.ChosenList == null)
            {
                // Set the list to default "none".
                storedViewModel.ChosenList = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).FirstOrDefault(l => l.Id == 7);
            }
        }

        [HttpGet]
        public string AddToList(string itemId)
        {
            LegoList list = null;

            string result = "item added to list";

            try
            {
                int listBridgeId = int.Parse(itemId);

                ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);

                if (listBridgeId != 0)
                {
                    // If the user doesn't have any lists, create one
                    if (this.context.LegoLists.Any(l => l.ApplicationUserId == currentUser.Id) == false)
                    {
                        this.context.LegoLists.Add(new LegoList
                        {
                            ApplicationUserId = currentUser.Id,
                            Name = "Favorites"
                        });

                        this.context.SaveChanges();
                    }

                    // If the stored chosen list has not been set
                    if (storedViewModel.ChosenList != null)
                    {
                        // Set the list to the chosen list
                        list = storedViewModel.ChosenList;
                    }

                    if (list != null)
                    {
                        list.LastModified = DateTime.Now;

                        LegoList listToSave = this.context.LegoLists.FirstOrDefault(l => l.Id == list.Id);

                        if (listToSave != null)
                        {
                            listToSave.LastModified = list.LastModified;
                        }

                        ListBridge listBridge = this.context.ListBridges.FirstOrDefault(l => l.LegoItemId == listBridgeId);

                        if (listBridge == null)
                        {
                            // Add a list bridge for this item
                            this.context.ListBridges.Add(new ListBridge
                            {
                                LegoListId = list.Id,
                                LegoItemId = listBridgeId
                            });
                        }
                        else
                        {
                            this.context.ListBridges.Remove(listBridge);
                        }

                        this.context.SaveChanges();
                    }
                }
            }
            catch (Exception e)
            {
                result = e.ToString();
            }

            return result;
        }

        public IActionResult Favorites()
        {
            InventoryViewModel viewModel = new InventoryViewModel();
            viewModel.View = "Set pricing";
            viewModel.AmountToDisplay = 10;
            viewModel.Type = 2;
            startingOver = true;
            this.LoadFavorites();
            this.IncrementPaging(viewModel);
            this.SetFavorites(viewModel);
            this.LoadLookups(viewModel);
            this.SetLookups(viewModel);
            this.ResetCount(viewModel);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Favorites(InventoryViewModel viewModel)
        {
            this.StoreViewModelData(viewModel);
            this.IncrementPaging(viewModel);
            this.SetFavorites(viewModel);
            this.SetLookups(viewModel);
            this.ResetCount(viewModel);

            return View(viewModel);
        }

        public IActionResult DataImport()
        {
            Importer importer = new Importer(context, environment);
            importer.SetBridgeDataImport();
            return View();
        }

        public IActionResult Index()
        {
            ApplicationUser currentUser = this.context.GetCurrentUser(HttpContext.User.Identity.Name);
            ViewBag.LegoLists = this.context.LegoLists.Include("ListBridges").OrderBy(l => l.Name).Where(l => l.ApplicationUserId == currentUser.Id).ToList();

            return View();
        }

        /// <summary>
        /// Performs search on full item list, calculated total results and pages.
        /// </summary>
        /// <returns>A value indicating whether or not the page number is equal to the total pages.</returns>
        [HttpGet]
        public object InitiateTotals()
        {
            object result = null;

            if (filterChanged && !startingOver)
            {
                try
                {
                    this.SetTotals();
                }
                catch (Exception e)
                {
                    result = new { status = "failure", IsFinalPage = "false", message = e.ToString() };
                }
            }

            if (storedViewModel.PageNumber == storedViewModel.TotalPages)
            {
                result = new { status = "success", IsFinalPage = "true" };
            }
            else
            {
                result = new { status = "success", IsFinalPage = "false" };
            }

            return result;
        }

        public IActionResult ItemList(int listId)
        {
            InventoryViewModel viewModel = new InventoryViewModel();
			viewModel.LegoItems = new List<LegoItem>();
            viewModel.View = "Set pricing";
            viewModel.AmountToDisplay = 10;
            viewModel.Type = 2;
            storedViewModel.Filter = string.Empty;
            this.StoreViewModelData(viewModel);
            startingOver = false;
            storedViewModel.View = "Favorites";
            this.LoadChosenList(listId.ToString());
            this.SetChosenList(viewModel);
            this.IncrementPaging(viewModel);
            this.LoadLookups(viewModel);
            this.SetLookups(viewModel);
			this.LoadFavorites();
            this.SetFavorites(viewModel);
            this.ResetCount(viewModel);
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult ItemList(InventoryViewModel viewModel)
        {
            this.StoreViewModelData(viewModel);
            this.SetChosenList(viewModel);
            this.IncrementPaging(viewModel);
			this.SetLookups(viewModel);
            this.SetFavorites(viewModel);
            this.ResetCount(viewModel);
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);
        }

        [HttpGet]
        public string GetTotalPages()
        {
            return storedViewModel.TotalPages.ToString();
        }

        [HttpGet]
        public string GetTotalResults()
        {
            return storedViewModel.TotalResults.ToString();
        }

        public IActionResult Inventory()
        {
            InventoryViewModel viewModel = new InventoryViewModel();
            viewModel.LegoItems = new List<LegoItem>();
            viewModel.View = "Location";
            viewModel.AmountToDisplay = 10;
            viewModel.Type = 2;
            storedViewModel.Filter = string.Empty;
            startingOver = true;
            this.LoadFavorites();
            this.LoadLookups(viewModel);
            this.SetLookups(viewModel);
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Inventory(InventoryViewModel viewModel)
        {
            this.StoreViewModelData(viewModel);
            this.IncrementPaging(viewModel);
            this.SetChosenList(viewModel);
            this.SetLookups(viewModel);
            this.SetLegoItems(viewModel);
            this.PlugInDelegates(viewModel);
            this.ResetCount(viewModel);
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);
        }

        public IActionResult Invoice()
        {
            return View();
        }

        public IActionResult MasterList(int? page)
        {
            InventoryViewModel viewModel = new InventoryViewModel();
            viewModel.LegoItems = new List<LegoItem>();
            viewModel.View = "Set pricing";
            viewModel.AmountToDisplay = 10;
            viewModel.Type = 2;
            storedViewModel.Filter = string.Empty;
            startingOver = true;
            this.LoadFavorites();
            this.LoadLookups(viewModel);
            this.SetLookups(viewModel);
            ViewBag.LegoLists = viewModel.LegoLists;

            return View(viewModel);

PlayWell/PlayWell/Views/Inventory/DataImport.cshtml
@{
    ViewData["Title"] = "DataImport";
}

<h2>DataImport</h2>

PlayWell/PlayWell/Views/Inventory/Index.cshtml
@{
    ViewData["Title"] = "Product List";
}

<div class="col-md-10 listview">
    <div class="panel panel-primary">
        <div class="panel-heading product-list-heading"><h3>Dashboard</h3></div>
        <div class="panel-body">
            @* SKU Total Panel *@
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        SKU Total
                    </div>
                    <div class="panel-body">
                        $0.00
                    </div>
                </div>
            </div>
            @* Inventory Total Panel *@
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Inventory Total
                    </div>
                    <div class="panel-body">
                        $0.00
                    </div>
                </div>
            </div>
            @* Value Total *@
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Value Total
                    </div>
                    <div class="panel-body">
                        $0.00
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PlayWell/PlayWell/Views/Inventory/Inventory.cshtml
@model PlayWell.Models.InventoryViewModels.InventoryViewModel

<div class="col-md-10">
    <div class="panel panel-primary">
        <div class="panel-heading"><h3>Inventory</h3></div>
            <div class="panel-body">
                @* Search/Filter *@
                <form id="searchForm" class="form-inline" asp-controller="Inventory" asp-action="Inventory">
                    <div class="form-group">
                        <label for="filter"><span class="glyphicon glyphicon-search"></span></label>
                        <input type="text" asp-for="Filter" class="form-control" id="filter" placeholder="Filter inventory">
                        <label for="setPartDropdown">Type:</label>
                        <select class="form-control" asp-for="Type" asp-items="@(new SelectList(Model.LegoTypes, "Id", "Name"))"></select>
                        <label for="viewsDropDown">Views:</label>
                        <select class="form-control" asp-for="View" id="chosenView">
                            <option>Location</option>
                            <option>Value</option>
                            <option>Set pricing</option>
                            @*<option>Recommended pricing</option>
                                <option>Sales history</option>*@
                        </select>
                        <label for="displayAmount">Display:</label>
                        <select class="form-control" asp-for="AmountToDisplay" id="displayAmount">
                            <option>10</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                        <button class="btn btn-default form-control" type="submit">Submit</button>
                    </div>
                </form>
                <br />
            </div>
            @* Result set information + Previous and next buttons *@
            @if (Model.LegoItems.Count != 0)
            {
                <div class="col-md-7">
                    <p>Total Results: <span id="TotalResults">@Model.TotalResults</span></p>
                    <p>Page Number: <span id="PageNumber">@Model.PageNumber</span> / <span id="TotalPages">@Model.TotalPages</span></p>
                </div>
                <div class="col-md-1">
                    <form asp-controller="Inventory"
                          asp-action="Inventory">
                        @Html.Hidden("Filter", Model.Filter)
                        @Html.Hidden("Type", Model.Type)
                        @Html.Hidden("View", Model.View)
                        @Html.Hidden("AmountToDisplay", Model.AmountToDisplay)
                        @Html.Hidden("LegoItems", Model.LegoItems)
                        @Html.Hidden("Counter", Model.Counter + 1)
                        @Html.Hidden("Previous", "Previous")
                        @if (Model.PageNumber == 1)
                        {
                            <button type="submit"
                                    class="btn btn-default disabled">
                                Previous
                            </button>
                        }
                        else
                        {
                            <button type="submit"
                                    class="btn btn-default">
                                Previous
                            </button>
                        }
                    </form>
                </div>
                <div class="col-md-1">
                    <form asp-controller="Inventory"
                          asp-action="Inventory">
                        @Html.Hidden("Filter", Model.Filter)
                        @Html.Hidden("Type", Model.Type)
                        @Html.Hidden("View", Model.View)
                        @Html.Hidden("AmountToDisplay", Model.AmountToDisplay)
                        @Html.Hidden("LegoItems", Model.LegoItems)
                        @Html.Hidden("Counter", Model.Counter + 1)
                        <button type="submit" class="btn btn-default nextButton"> Next </button>
                    </form>
                </div>

                <div class="col-md-3">
                    <label for="chosenList">List:</label>
                    <select id="chosenList" class="form-control" style="display:inline-block;width:200px;">
                        @if (Model.LegoLists != null)
                        {
                            @foreach (LegoList l in Model.LegoLists)
                            {
                                @if (l.Id == Model.ChosenList.Id)
                                {
                                    <option selected value="@l.Id">@l.Name</option>
                                }
                                else
                                {
                                    <option value="@l.Id">@l.Name</option>

                                }
                            }
                        }
                    </select>
                </div>
            }

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="35%">Description</th>
                        <th>Part&nbsp;ID</th>
                        @if (Model.View == "Location")
                        {
                            <th>Primary Location</th>
                            <th>Qty</th>
                        }
                        @if (Model.View == "Value")
                        {
                            <th>Cost</th>
                            <th>Ext.&nbsp;Cost</th>
                            <th>Price</th>
                            <th>Ext.&nbsp;Price</th>
                        }
                        @if (Model.View == "Set pricing")
                        {
                            <th>Avg&nbsp;cost</th>
                            <th>Avg&nbsp;Price</th>
                            <th>Method</th>
                            <th>Sugg&nbsp;Price</th>
                            <th>Price</th>
                        }
                        @if (Model.ChosenList != null)
                        {
                            @if (Model.ChosenList.Id != 7)
                            {
                                <th></th>
                            }
                        }
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.AmountToDisplay; i++)
                    {
                        <tr>
                            @if (Model.LegoItems.Count != 0)
                            {
                                <td width="35%">
                                    @foreach (LegoColor lc in Model.LegoColors)
                                    {
                                        @if (lc.Id == Model.LegoItems[i].LegoColorId)
                                        {
                                            @lc.Name
                                        }
                                    } : @Model.LegoItems[i].Description
                                </td>
                                <td>@Model.LegoItems[i].BrickLinkId</td>
                                @if (Model.View == "Location")
                                {
                                    <td>Location</td>
                                    <td>@Model.LegoItems[i].ForSaleQuantityTotal</td>
                                }
                                @if (Model.View == "Value")
                                {
                                    <td>Cost</td>
                                    <td>Extended Cost</td>
                                    <td>@Model.LegoItems[i].SoldAveragePrice</td>
                                    <td>Extended Price</td>
                                }
                                @if (Model.View == "Set pricing")
                                {
                                    <td>0.00</td>
                                    <td>0.00</td>
                                    <td>
                                        <select id="PricingMethod_@Model.LegoItems[i].Id" class="pricingMethod form-control">
                                            @if (Model.PricingMethods != null)
                                            {
                                                @foreach (PricingMethod p in Model.PricingMethods)
                                                {
                                                    @if (p.Id == @Model.LegoItems[i].PricingMethodId)
                                                    {
                                                        <option selected value="@p.Id">@p.Name</option>
                                                    }
                                                    else
                                                    {
                                                        <option value="@p.Id">@p.Name</option>
                                                    }
                                                }
                                            }
                                        </select>
                                    </td>
                                    <td><span id="SuggestedPrice_@Model.LegoItems[i].Id">@Model.LegoItems[i].SuggestedPrice</span></td>
                                    <td>
                                        <input type="number" class="priceChange form-control" id="Price_@Model.LegoItems[i].Id" value="@Model.LegoItems[i].Price">
                                    </td>
                                }
                                @if (Model.ChosenList != null)
                                {
                                    @if (Model.ChosenList.Id != 7)
                                    {
                                        <td>
                                            @if (Model.LegoItems[i].IsFavorite)
                                            {
                                                <i id="ListBridge_@Model.LegoItems[i].Id" class="favoriteStar glyphicon glyphicon-star bigger-star"></i>
                                            }
                                            else
                                            {
                                                <i id="ListBridge_@Model.LegoItems[i].Id" class="favoriteStar glyphicon glyphicon-star-empty bigger-star"></i>
                                            }
                                        </td>
                                    }
                                }
                            }
                        </tr>
                    }
                    @if (Model.LegoItems.Count == 0)
                    {
                        <tr>
                            <td colspan="14">
                                No data to display.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @if (Model.LegoItems.Count != 0)
        {
            <div class="col-md-2">

                <form asp-controller="Inventory"
                      asp-action="Inventory">
                    @Html.Hidden("Filter", Model.Filter)
                    @Html.Hidden("Type", Model.Type)
                    @Html.Hidden("View", Model.View)
                    @Html.Hidden("AmountToDisplay", Model.AmountToDisplay)
                    @Html.Hidden("LegoItems", Model.LegoItems)
                    @Html.Hidden("Counter", Model.Counter + 1)
                    @Html.Hidden("Previous", "Previous")
                    @if (Model.PageNumber == 1)
                {
                        <button type="submit"
                                class="btn btn-default disabled">
                            Previous
                        </button>
                    }
                    else
                    {
                        <button type="submit"
                                class="btn btn-default">
                            Previous
                        </button>
                    }
                </form>

            </div>
            <div class="col-md-2">
                @if (Model.PageNumber != Model.TotalPages)
                {
                    <form asp-controller="Inventory"
                          asp-action="Inventory">
                        @Html.Hidden("Filter", Model.Filter)
                        @Html.Hidden("Type", Model.Type)
                        @Html.Hidden("View", Model.View)
                        @Html.Hidden("AmountToDisplay", Model.AmountToDisplay)
                        @Html.Hidden("LegoItems", Model.LegoItems)
                        @Html.Hidden("Counter", Model.Counter + 1)
                        <button type="submit" class="btn btn-default nextButton"> Next </button>
                    </form>
                }
            </div>
        }

    </div>